# Generated by Django 5.1.4 on 2025-01-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
